services:
  postgres:
    image: postgres:16-alpine
    container_name: sinutre-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sinutre
      POSTGRES_PASSWORD: sinutre
      POSTGRES_DB: sinutre
    ports:
      - "5432:5432"
    volumes:
      - sinutre_pgdata:/var/lib/postgresql/data

volumes:
  sinutre_pgdata:
